export const ROLES = [
  { id: "1", name: "Super Administrator", slug: "super-administrator", level: 10, description: "Full system access" },
  { id: "2", name: "Presidential Candidate", slug: "presidential-candidate", level: 10, description: "View-only global access" },
  { id: "3", name: "Campaign Executive Director", slug: "campaign-executive-director", level: 9, description: "Executive oversight" },
  { id: "4", name: "National Campaign Manager", slug: "national-campaign-manager", level: 9, description: "National operations" },
  { id: "5", name: "National Organising Director", slug: "national-organising-director", level: 8, description: "Field organization" },
  { id: "6", name: "County Coordinator", slug: "county-coordinator", level: 7, description: "County-level management" },
  { id: "7", name: "Constituency Coordinator", slug: "constituency-coordinator", level: 6, description: "Constituency-level management" },
  { id: "8", name: "Ward Coordinator", slug: "ward-coordinator", level: 5, description: "Ward-level management" },
  { id: "9", name: "Polling Centre Coordinator", slug: "polling-centre-coordinator", level: 4, description: "Centre-level management" },
  { id: "10", name: "Polling Station Agent", slug: "polling-station-agent", level: 3, description: "Station operations" },
  { id: "11", name: "Backup Polling Agent", slug: "backup-polling-agent", level: 3, description: "Backup station operations" },
  { id: "12", name: "Volunteer", slug: "volunteer", level: 2, description: "General volunteer" },
  { id: "13", name: "Donor", slug: "donor", level: 2, description: "Financial contributor" },
  { id: "14", name: "Finance Officer", slug: "finance-officer", level: 7, description: "Financial tracking" },
  { id: "15", name: "Treasurer", slug: "treasurer", level: 8, description: "Financial management" },
  { id: "16", name: "Communications Officer", slug: "communications-officer", level: 6, description: "Public relations" },
  { id: "17", name: "Content Approver", slug: "content-approver", level: 7, description: "Content approval" },
  { id: "18", name: "Legal Officer", slug: "legal-officer", level: 8, description: "Legal oversight" },
  { id: "19", name: "Verification Officer", slug: "verification-officer", level: 6, description: "Data verification" },
  { id: "20", name: "Data Protection Officer", slug: "data-protection-officer", level: 8, description: "Privacy compliance" },
  { id: "21", name: "Security Administrator", slug: "security-administrator", level: 9, description: "Security management" },
  { id: "22", name: "Auditor", slug: "auditor", level: 8, description: "System auditing" },
  { id: "23", name: "Call Centre Agent", slug: "call-centre-agent", level: 3, description: "Call operations" },
  { id: "24", name: "Public Supporter", slug: "public-supporter", level: 1, description: "General supporter" },
];
