import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import rolesRouter from "./roles";
import geographyRouter from "./geography";
import dashboardRouter from "./dashboard";
import configRouter from "./config";
import auditRouter from "./audit";
import volunteersRouter from "./volunteers";
import supportersRouter from "./supporters";
import trainingRouter from "./training";
import publicPortalRouter from "./publicPortal";
import dataRequestsRouter from "./dataRequests";
import coordinatorRouter from "./coordinator";
import financeRouter from "./finance";
import communicationsRouter from "./communications";
import contentLibraryRouter from "./contentLibrary";
import eventsMgmtRouter from "./eventsMgmt";
import rapidResponseRouter from "./rapidResponse";
import storageRouter from "./storage";
import electionAdminRouter from "./electionAdmin";
import pollingStationsMgmtRouter from "./pollingStationsMgmt";
import pollingAgentsMgmtRouter from "./pollingAgentsMgmt";
import electionResultsRouter from "./electionResults";
import tallyRouter from "./tally";
import electionIncidentsRouter from "./electionIncidents";
import electionDisputesRouter from "./electionDisputes";
import transparencyPortalRouter from "./transparencyPortal";
import commandCentreRouter from "./commandCentre";
import reportingRouter from "./reporting";
import complianceRouter from "./compliance";
import privilegedAccessRouter from "./privilegedAccess";
import aspirantsRouter from "./aspirants";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use("/users", usersRouter);
router.use("/roles", rolesRouter);
router.use("/geography", geographyRouter);
router.use("/dashboard", dashboardRouter);
router.use("/config", configRouter);
router.use("/audit", auditRouter);
router.use("/volunteers", volunteersRouter);
router.use("/supporters", supportersRouter);
router.use("/training", trainingRouter);
router.use("/public", publicPortalRouter);
router.use("/data-requests", dataRequestsRouter);
router.use("/coordinator", coordinatorRouter);
router.use("/finance", financeRouter);
router.use("/communications", communicationsRouter);
router.use("/content", contentLibraryRouter);
router.use("/events-mgmt", eventsMgmtRouter);
router.use("/rapid-response", rapidResponseRouter);
router.use("/election-admin", electionAdminRouter);
router.use("/polling-stations-mgmt", pollingStationsMgmtRouter);
router.use("/polling-agents", pollingAgentsMgmtRouter);
router.use("/election-results", electionResultsRouter);
router.use("/tally", tallyRouter);
router.use("/election-incidents", electionIncidentsRouter);
router.use("/election-disputes", electionDisputesRouter);
router.use("/transparency", transparencyPortalRouter);
router.use("/command-centre", commandCentreRouter);
router.use("/reporting", reportingRouter);
router.use("/compliance", complianceRouter);
router.use("/privileged-access", privilegedAccessRouter);
router.use("/aspirants", aspirantsRouter);

export default router;
